{\rtf1\ansi\ansicpg1252\cocoartf2822
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 # This file is a Render Blueprint. It defines the services to deploy.\
# Learn more: https://render.com/docs/blueprint\
\
services:\
  - type: web\
    name: solana-burn-monitor\
    env: python\
    buildCommand: "pip install -r requirements.txt"\
    startCommand: "python main.py"\
    # Port is not explicitly needed for non-web servers, but Render requires it for 'web' services.\
    # The bot script itself does not expose a port for HTTP traffic.\
    # However, Render's web service type will listen on a port (default 10000 or specified by PORT env var)\
    # This is useful for uptime monitoring tools like Uptime Robot.\
    port: 10000\
    envVars:\
      - key: TELEGRAM_BOT_TOKEN\
        sync: false # Set to true to sync from Render dashboard\
      - key: TELEGRAM_CHAT_ID\
        sync: false\
      - key: TOKEN_MINT_ADDRESS\
        sync: false\
      - key: SOLANA_RPC_URL\
        value: "https://api.mainnet-beta.solana.com" # Default, override if you have a private one\
      - key: SOLANA_WS_URL\
        value: "wss://api.mainnet-beta.solana.com" # Default, override if you have a private one\
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON_BASE64\
        sync: false\
    # Minimum instance count to ensure the service is always running.\
    # Set to 1 to keep it online.\
    minInstances: 1\
    # You might want to enable health checks to restart the service if it crashes.\
    # Since this is not a web server, a simple port check is sufficient for Uptime Robot.\
    # The health check path for Render's internal checks can be something like /healthz if you add a simple Flask/FastAPI endpoint.\
    # But for a background worker, Uptime Robot will just ping the public URL.\
    healthCheckPath: /\
\
}