# This file is a Render Blueprint. It defines the services to deploy.
# Learn more: https://render.com/docs/blueprint

services:
  - type: web
    name: solana-burn-monitor
    env: docker # Use Docker environment to utilize Dockerfile
    plan: free
    dockerCommand: python main.py # Matches Dockerfile CMD
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: TOKEN_MINT_ADDRESS
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON_BASE64
        sync: false
      - key: SOLANA_RPC_URL
        value: "https://mainnet.helius-rpc.com/?api-key=<YOUR_HELIUS_API_KEY>"
      - key: SOLANA_WS_URL
        value: "wss://mainnet.helius-rpc.com/?api-key=<YOUR_HELIUS_API_KEY>"
    port: 10000 # Flask port in main.py
    healthCheckPath: / # Matches Flask health check endpoint
    minInstances: 1
