# This file is a Render Blueprint. It defines the services to deploy.
# Learn more: https://render.com/docs/blueprint

services:
  - type: web # Changed back to 'web'
    name: solana-burn-monitor
    env: python
    buildCommand: "pip install -r requirements.txt"
    # Changed startCommand to use waitress to serve the Flask app
    startCommand: "waitress-serve main:app_flask"
    port: 10000 # Specify the port Flask will listen on
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: TOKEN_MINT_ADDRESS
        sync: false
      - key: SOLANA_RPC_URL
        value: "https://api.mainnet-beta.solana.com"
      - key: SOLANA_WS_URL
        value: "wss://api.mainnet-beta.solana.com"
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON_BASE64
        sync: false
    minInstances: 1
    healthCheckPath: / # This health check will hit the Flask app's '/' route
